//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ExaminationSchedules')
export class ExaminationSchedulesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Grade: string;

  @Column('text', { nullable: true })
  Subjects: string;

  @Column('date', { nullable: true })
  Date: Date;

  @Column('text', { nullable: true })
  Time: string;
}
