//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('QuestionPapers')
export class QuestionPapersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Grade: string;

  @Column('text', { nullable: true })
  Subjects: string;

  @Column('text', { nullable: true })
  Year: string;

  @Column('text', { nullable: true })
  Content: string;
}
