//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { SyllabusEntity } from './db/Syllabus.entity';
import { NotesEntity } from './db/Notes.entity';
import { QuestionPapersEntity } from './db/QuestionPapers.entity';
import { ExaminationSchedulesEntity } from './db/ExaminationSchedules.entity';
import { SchoolsEntity } from './db/Schools.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      SyllabusEntity,
      NotesEntity,
      QuestionPapersEntity,
      ExaminationSchedulesEntity,
      SchoolsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Syllabus: [
        {
          Grade: 'Grade 9',
          Subjects:
            'Agriculture Extension and Computer Science, Principle of Agronomy, Basic Horticulture, Plant protection',
        },
        {
          Grade: 'Grade 10',
          Subjects:
            'Industrial Agriculture and fish Culture, Food Crop Production, Horticultural Crop Production, Floriculture and Nursery Production',
        },
        {
          Grade: 'Grade 11',
          Subjects:
            'Agricultural entomology, Farm Machinery and Seed Technology, Soil Fertility and Nutrient Management, Commercial Fruit Crop Production and Post-Harvest Technology',
        },
        {
          Grade: 'Grade 12',
          Subjects:
            'Agri-Economics, Industrial Crop Production, Plant Pathology and Mushroom Production, Vegetable and Medicinal Plant Production',
        },
        {
          Grade: 'Grade 9',
          Subjects: 'Basic Horticulture and Plant protection',
        },
      ],
      Notes: [
        {
          Grade: 'Grade 9',
          Subjects: 'Agriculture Extension and Computer Science',
          Content:
            'Introduction to basic computer science concepts and their applications in agriculture extension.',
        },
        {
          Grade: 'Grade 10',
          Subjects: 'Food Crop Production',
          Content:
            'Detailed study on the methods and techniques involved in the production of major food crops.',
        },
        {
          Grade: 'Grade 11',
          Subjects: 'Soil Fertility and Nutrient Management',
          Content:
            'Exploration of soil fertility principles and practices for effective nutrient management in crop production.',
        },
        {
          Grade: 'Grade 12',
          Subjects: 'Agri-Economics',
          Content:
            'Understanding the economic principles applicable to the agricultural sector, including market analysis and farm management strategies.',
        },
        {
          Grade: 'Grade 11',
          Subjects:
            'Commercial Fruit Crop Production and Post-Harvest Technology',
          Content:
            'Comprehensive guide on the cultivation of commercial fruit crops and the technologies used in post-harvest processing.',
        },
      ],
      QuestionPapers: [
        {
          Grade: 'Grade 10',
          Subjects: 'Industrial Agriculture and Fish Culture',
          Year: '2020',
          Content:
            'Describe the process of fish farming in detail. Explain the types of fish culture systems.',
        },
        {
          Grade: 'Grade 11',
          Subjects: 'Soil Fertility and Nutrient Management',
          Year: '2021',
          Content:
            'Discuss the importance of soil testing in nutrient management. How can farmers improve soil fertility?',
        },
        {
          Grade: 'Grade 12',
          Subjects: 'Plant Pathology and Mushroom Production',
          Year: '2019',
          Content:
            'Explain the lifecycle of a common plant pathogen and its impact on mushroom production. Suggest preventive measures.',
        },
        {
          Grade: 'Grade 9',
          Subjects: 'Basic Horticulture',
          Year: '2022',
          Content:
            'What is horticulture? Discuss its significance in agriculture and the environment.',
        },
        {
          Grade: 'Grade 11',
          Subjects:
            'Commercial Fruit Crop Production and Post-Harvest Technology',
          Year: '2020',
          Content:
            'Describe the steps involved in the production of a commercial fruit crop of your choice. Also, explain the post-harvest technologies available for this crop.',
        },
      ],
      ExaminationSchedules: [
        {
          Grade: 'Grade 11',
          Subjects: 'Agricultural entomology',
          Date: '2023-11-15T09:00:00Z',
          Time: '09:00 AM',
        },
        {
          Grade: 'Grade 12',
          Subjects: 'Agri-Economics',
          Date: '2023-11-16T09:00:00Z',
          Time: '09:00 AM',
        },
        {
          Grade: 'Grade 10',
          Subjects: 'Food Crop Production',
          Date: '2023-11-17T09:00:00Z',
          Time: '09:00 AM',
        },
        {
          Grade: 'Grade 9',
          Subjects: 'Basic Horticulture',
          Date: '2023-11-18T09:00:00Z',
          Time: '09:00 AM',
        },
        {
          Grade: 'Grade 12',
          Subjects: 'Vegetable and Medicinal Plant Production',
          Date: '2023-11-19T09:00:00Z',
          Time: '09:00 AM',
        },
      ],
      Schools: [
        {
          name: 'Green Valley High',
          location: 'Kathmandu',
          gradeLevels: '9-12',
        },
        {
          name: 'Everest Science Academy',
          location: 'Pokhara',
          gradeLevels: '9-12',
        },
        {
          name: 'Himalayan Public School',
          location: 'Lalitpur',
          gradeLevels: '9-12',
        },
        {
          name: 'Shangri-La Secondary School',
          location: 'Bhaktapur',
          gradeLevels: '9-12',
        },
        {
          name: 'Lotus International College',
          location: 'Butwal',
          gradeLevels: '11-12',
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('SyllabusEntity', data.Syllabus);
      await this.SeedResource('NotesEntity', data.Notes);
      await this.SeedResource('QuestionPapersEntity', data.QuestionPapers);
      await this.SeedResource(
        'ExaminationSchedulesEntity',
        data.ExaminationSchedules,
      );
      await this.SeedResource('SchoolsEntity', data.Schools);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
