//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  SyllabusList,
  SyllabusCreate,
  SyllabusEdit,
} from './resources/Syllabus';
import { NotesList, NotesCreate, NotesEdit } from './resources/Notes';
import {
  QuestionPapersList,
  QuestionPapersCreate,
  QuestionPapersEdit,
} from './resources/QuestionPapers';
import {
  ExaminationSchedulesList,
  ExaminationSchedulesCreate,
  ExaminationSchedulesEdit,
} from './resources/ExaminationSchedules';
import { SchoolsList, SchoolsCreate, SchoolsEdit } from './resources/Schools';
import SyllabusIcon from '@mui/icons-material/MenuBook';
import NotesIcon from '@mui/icons-material/Note';
import QuestionPapersIcon from '@mui/icons-material/Assignment';
import ExaminationSchedulesIcon from '@mui/icons-material/Schedule';
import SchoolsIcon from '@mui/icons-material/School';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a0313d1be">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Syllabus"
          options={{ label: 'Syllabus' }}
          list={SyllabusList}
          create={SyllabusCreate}
          edit={SyllabusEdit}
          recordRepresentation="Grade"
          icon={SyllabusIcon}
        />
        <Resource
          name="Notes"
          options={{ label: 'Notes' }}
          list={NotesList}
          create={NotesCreate}
          edit={NotesEdit}
          recordRepresentation="Content"
          icon={NotesIcon}
        />
        <Resource
          name="QuestionPapers"
          options={{ label: 'Question Papers' }}
          list={QuestionPapersList}
          create={QuestionPapersCreate}
          edit={QuestionPapersEdit}
          recordRepresentation="Year"
          icon={QuestionPapersIcon}
        />
        <Resource
          name="ExaminationSchedules"
          options={{ label: 'Examination Schedules' }}
          list={ExaminationSchedulesList}
          create={ExaminationSchedulesCreate}
          edit={ExaminationSchedulesEdit}
          recordRepresentation="Date"
          icon={ExaminationSchedulesIcon}
        />
        <Resource
          name="Schools"
          options={{ label: 'Schools' }}
          list={SchoolsList}
          create={SchoolsCreate}
          edit={SchoolsEdit}
          recordRepresentation="name"
          icon={SchoolsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
