//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Neb Plant Science" />
    <CardContent>
      This application will contain syllabus, of class 9,10, 11 and 12 and this
      app will also contain some notes related to different subjects that are
      taught in class 9, 10,11 and 12 and this app will also contain old
      examination questions papers and this app will also publish different
      examination schedules all above informations will be kept in classwise
      categories
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
