//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';
import grOriginal from 'ra-language-greek';

const enResources = {
  resources: {
    Syllabus: {
      name: 'Syllabus',
      fields: { Grade: 'Grade', Subjects: 'Subjects', id: 'id' },
    },
    Notes: {
      name: 'Notes',
      fields: {
        Grade: 'Grade',
        Subjects: 'Subjects',
        Content: 'Content',
        id: 'id',
      },
    },
    QuestionPapers: {
      name: 'Question Papers',
      fields: {
        Grade: 'Grade',
        Subjects: 'Subjects',
        Year: 'Year',
        Content: 'Content',
        id: 'id',
      },
    },
    ExaminationSchedules: {
      name: 'Examination Schedules',
      fields: {
        Grade: 'Grade',
        Subjects: 'Subjects',
        Date: 'Date',
        Time: 'Time',
        id: 'id',
      },
    },
    Schools: {
      name: 'Schools',
      fields: {
        name: 'Name',
        location: 'Location',
        gradeLevels: 'Grade Levels',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Syllabus: {
      name: 'Syllabus (fr)',
      fields: { Grade: 'Grade (fr)', Subjects: 'Subjects (fr)', id: 'id' },
    },
    Notes: {
      name: 'Notes (fr)',
      fields: {
        Grade: 'Grade (fr)',
        Subjects: 'Subjects (fr)',
        Content: 'Content (fr)',
        id: 'id',
      },
    },
    QuestionPapers: {
      name: 'Question Papers (fr)',
      fields: {
        Grade: 'Grade (fr)',
        Subjects: 'Subjects (fr)',
        Year: 'Year (fr)',
        Content: 'Content (fr)',
        id: 'id',
      },
    },
    ExaminationSchedules: {
      name: 'Examination Schedules (fr)',
      fields: {
        Grade: 'Grade (fr)',
        Subjects: 'Subjects (fr)',
        Date: 'Date (fr)',
        Time: 'Time (fr)',
        id: 'id',
      },
    },
    Schools: {
      name: 'Schools (fr)',
      fields: {
        name: 'Name (fr)',
        location: 'Location (fr)',
        gradeLevels: 'Grade Levels (fr)',
        id: 'id',
      },
    },
  },
};
const grResources = {
  resources: {
    Syllabus: {
      name: 'Syllabus (gr)',
      fields: { Grade: 'Grade (gr)', Subjects: 'Subjects (gr)', id: 'id' },
    },
    Notes: {
      name: 'Notes (gr)',
      fields: {
        Grade: 'Grade (gr)',
        Subjects: 'Subjects (gr)',
        Content: 'Content (gr)',
        id: 'id',
      },
    },
    QuestionPapers: {
      name: 'Question Papers (gr)',
      fields: {
        Grade: 'Grade (gr)',
        Subjects: 'Subjects (gr)',
        Year: 'Year (gr)',
        Content: 'Content (gr)',
        id: 'id',
      },
    },
    ExaminationSchedules: {
      name: 'Examination Schedules (gr)',
      fields: {
        Grade: 'Grade (gr)',
        Subjects: 'Subjects (gr)',
        Date: 'Date (gr)',
        Time: 'Time (gr)',
        id: 'id',
      },
    },
    Schools: {
      name: 'Schools (gr)',
      fields: {
        name: 'Name (gr)',
        location: 'Location (gr)',
        gradeLevels: 'Grade Levels (gr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);
const gr = mergeTranslations(grOriginal, grResources);

const translations = { en, fr, gr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
    { locale: 'gr', name: 'Ελληνικά' },
  ],
);
